CREATE TYPE INTIMACYTYPE AS ENUM ('TIE', 'PRINCIPLE');
CREATE TYPE INTIMACYLEVEL AS ENUM ('MINOR', 'MAJOR', 'DEFINING');

CREATE TABLE intimacies (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    character_id INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    intimacy_type INTIMACYTYPE NOT NULL,
    level INTIMACYLEVEL NOT NULL,
    description TEXT NOT NULL
);