CREATE TABLE campaign_players (
    id BIGSERIAL PRIMARY KEY,
    campaign_id BIGSERIAL NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    player_id BIGSERIAL NOT NULL REFERENCES players(id) ON DELETE CASCADE
);