CREATE TYPE ATTRIBUTENAME AS ENUM ('STRENGTH', 'DEXTERITY', 'STAMINA', 
'CHARISMA', 'MANIPULATION', 'APPEARANCE', 'PERCEPTION', 'INTELLIGENCE', 'WITS');

CREATE TABLE attributes (
    character_id INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    name ATTRIBUTENAME NOT NULL,
    dots SMALLINT NOT NULL CHECK (dots >= 1),
    PRIMARY KEY (character_id, name)
);